import {
  HeartPulse, MonitorSmartphone, Code2, Megaphone, Smartphone, CreditCard, Boxes,
} from 'lucide-react'

// Shared service catalog used by the home services grid and the dynamic
// /services/[slug] detail pages.
export const SERVICES = [
  {
    slug: 'health-it',
    icon: HeartPulse,
    title: 'Health IT',
    tagline: 'Custom software for modern healthcare',
    image: 'https://images.pexels.com/photos/5452301/pexels-photo-5452301.jpeg',
    short: 'Custom software for the healthcare industry’s ever-increasing technological needs.',
    overview: 'Our Health IT experts build HIPAA-conscious platforms that streamline clinical and administrative workflows — from EHR/EMR integrations and patient portals to telehealth and practice management. We help providers deliver better outcomes while reducing operational overhead.',
    features: ['EHR / EMR integration', 'Patient portals & scheduling', 'Telehealth solutions', 'Practice & billing management', 'Interoperability (HL7 / FHIR)', 'Secure data compliance'],
    benefits: ['Reduce administrative workload', 'Improve patient engagement', 'Faster, data-driven decisions', 'Scalable & secure infrastructure'],
  },
  {
    slug: 'website-design',
    icon: MonitorSmartphone,
    title: 'Website Design',
    tagline: 'Designs that convert visitors to clients',
    image: 'https://images.pexels.com/photos/326514/pexels-photo-326514.jpeg',
    short: 'Responsive, high-converting website designs crafted around your brand and audience.',
    overview: 'We craft pixel-perfect, responsive designs that reflect your brand and guide visitors toward action. Every layout is built mobile-first with accessibility and conversion in mind.',
    features: ['Custom UI/UX design', 'Mobile-first & responsive', 'Brand-aligned visual system', 'Landing pages & funnels', 'Accessibility (WCAG)', 'Design-to-code handoff'],
    benefits: ['Stronger first impressions', 'Higher conversion rates', 'Consistent brand identity', 'Great experience on any device'],
  },
  {
    slug: 'web-development',
    icon: Code2,
    title: 'Web Development',
    tagline: 'Robust web applications, built to scale',
    image: 'https://images.pexels.com/photos/7988114/pexels-photo-7988114.jpeg',
    short: 'A highly qualified team with advanced technical knowledge to build robust web applications.',
    overview: 'From marketing sites to complex SaaS platforms, our engineers build fast, secure and maintainable web applications using modern frameworks and best practices.',
    features: ['Modern frameworks (React/Next.js)', 'Custom web applications', 'API & third-party integrations', 'Database architecture', 'Performance optimization', 'Ongoing maintenance & support'],
    benefits: ['Blazing-fast performance', 'Secure & maintainable code', 'Seamless integrations', 'Built to grow with you'],
  },
  {
    slug: 'digital-marketing',
    icon: Megaphone,
    title: 'Digital Marketing',
    tagline: 'Grow your presence, grow your revenue',
    image: 'https://images.pexels.com/photos/7651801/pexels-photo-7651801.jpeg',
    short: 'Expand your business identity and increase your online presence with data-driven marketing.',
    overview: 'We combine strategy, creativity and analytics to increase your visibility and drive qualified leads — across search, social and paid media, all measured against real ROI.',
    features: ['SEO & content strategy', 'Google & Meta ad campaigns', 'Social media management', 'Email & funnel automation', 'Analytics & reporting', 'Conversion rate optimization'],
    benefits: ['More qualified leads', 'Higher return on ad spend', 'Stronger brand awareness', 'Clear, measurable results'],
  },
  {
    slug: 'mobile-apps',
    icon: Smartphone,
    title: 'Mobile Apps',
    tagline: 'Native-quality apps for iOS & Android',
    image: 'https://images.pexels.com/photos/32944547/pexels-photo-32944547.jpeg',
    short: 'Enhance user experience with custom mobile applications tailored for your business.',
    overview: 'Our developers have deep expertise across major mobile platforms. We design and build intuitive, high-performance apps that keep your customers engaged.',
    features: ['iOS & Android development', 'Cross-platform (React Native)', 'Intuitive UX design', 'Push notifications', 'Offline & sync support', 'App store deployment'],
    benefits: ['Reach customers anywhere', 'Higher engagement & retention', 'Smooth, native-like experience', 'Faster time to market'],
  },
  {
    slug: 'pos-application',
    icon: CreditCard,
    title: 'POS Application',
    tagline: 'Everything you need to run your store',
    image: 'https://images.pexels.com/photos/12935100/pexels-photo-12935100.jpeg',
    short: 'Simplify operations with POS software that has everything you need to run a retail store.',
    overview: 'Our POS software simplifies day-to-day retail operations — from lightning-fast checkout and inventory tracking to sales analytics and multi-outlet management, online and offline.',
    features: ['Fast, reliable checkout', 'Inventory management', 'GST-ready billing', 'Multi-outlet support', 'Offline mode with sync', 'Sales & stock analytics'],
    benefits: ['Faster checkouts', 'Fewer stock errors', 'Real-time business insights', 'Works even without internet'],
  },
  {
    slug: 'erp-solutions',
    icon: Boxes,
    title: 'ERP Solutions',
    tagline: 'Run your whole business from one dashboard',
    image: 'https://images.pexels.com/photos/30547618/pexels-photo-30547618.jpeg',
    short: 'Unified ERP to run finance, inventory, HR & operations from one intelligent dashboard.',
    overview: 'Bring finance, inventory, HR, sales and operations together in a single intelligent platform. Our ERP solutions automate workflows and give leadership a real-time view of the entire business.',
    features: ['Finance & accounting', 'Inventory & supply chain', 'HR & payroll', 'Sales & CRM', 'Custom workflow automation', 'Role-based dashboards'],
    benefits: ['One source of truth', 'Automated operations', 'Better cross-team visibility', 'Data-driven leadership'],
  },
]

export const getService = (slug) => SERVICES.find((s) => s.slug === slug)
